- hosts: localhost
  become: true
  gather_facts: false
  vars:
    dotfiles: https://github.com/marcobompani/dotfiles
    home_dir: /home/marco
    home_user: marco

  tasks:
    - name: Install core pacman packages
      pacman:
        name:
          - base-devel
          - tmux
          - htop
          - tcpdump
          - git
          - python-pip
          - python-pexpect
          - trash-cli
          - xsel
          - net-tools
          - nfs-utils
          - exa
          - wget
          - curl
          - dnsutils
          - findutils
          - unzip
          - openssl
          - mlocate
          - dunst
          - speedtest-cli
          - neovim
          - man-db
          - man-pages
          - mingw-w64-gcc
          - mingw-w64-binutils
          - pyenv
          - python-pipenv
          - cron
        state: present
        update_cache: true
      tags: install, packages, pacman

    - name: Install utilities
      pacman:
        name:
          - xorg
          - lightdm
          - rofi
          - alacritty
          - i3-wm
          - i3-gaps
          - keepass
        state: present
        update_cache: true
      tags: install, packages, pacman

    - name: Clone yay
      git:
        repo: https://aur.archlinux.org/yay.git
        dest: /opt/yay
      tags: yay, git

    - name: Prep yay
      shell: chown -R {{ home_user }}:{{ home_user }} /opt/yay
      tags: yay

    - name: Install yay
      command: makepkg --noconfirm -si
      become: false
      args:
        chdir: /opt/yay
      tags: yay

    - name: Run yay
      expect:
        command: yay
        timeout: 300
        responses:
          Y/n: Y
      become: true
      tags: yay

    - name: Install AUR packages
      command: yay --noconfirm --needed -S {{ item }}
      with_items: 
        - zoom
        - slack-desktop
        - google-chrome
        - polybar
      become_user: "{{ home_user }}"
      tags: aur, install, packages

    - name: Clone dotfiles
      git:
        repo: "{{ dotfiles }}"
        dest: "{{ home_dir }}/dotfiles"
      tags: git, dotfiles

    - name: Prep dotfiles
      shell: chown -R {{ home_user }}:{{ home_user }} {{ home_dir }}/dotfiles
      tags: dotfiles

    - name: Make directories
      file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ home_user }}"
        group: "{{ home_user }}"
        mode: "0755"
      with_items:
        - { path: "{{ home_dir }}/.config" }
        - { path: "{{ home_dir }}/.config/polybar" }
        - { path: "{{ home_dir }}/.config/nvim" }
        - { path: "{{ home_dir }}/.config/alacritty" }
        - { path: "{{ home_dir }}/.config/rofi" }
        - { path: "{{ home_dir }}/.config/dunst" }
        - { path: "{{ home_dir }}/.config/i3" }
        - { path: "{{ home_dir }}/.config/picom" }
        - { path: "{{ home_dir }}/.local/share/nvim/backup" }
      tags: dotfiles, folders

    - name: Link dotfiles
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ home_user }}"
        group: "{{ home_user }}"
        mode: "0644"
        state: link
      with_items:
        - { src: "{{ home_dir }}/dotfiles/tmux/tmux.conf", dest: "{{ home_dir }}/.tmux.conf" }
        - { src: "{{ home_dir }}/dotfiles/nvim/init.vim", dest: "{{ home_dir }}/.config/nvim/init.vim" }
        - { src: "{{ home_dir }}/dotfiles/i3/config", dest: "{{ home_dir }}/.config/i3/config" }
        - { src: "{{ home_dir }}/dotfiles/aliases/bash_aliases", dest: "{{ home_dir }}/.bash_aliases" }
        - { src: "{{ home_dir }}/dotfiles/alacritty/alacritty.yml", dest: "{{ home_dir }}/.config/alacritty/alacritty.yml" }
        - { src: "{{ home_dir }}/dotfiles/polybar/config", dest: "{{ home_dir }}/.config/polybar/config" }
        - { src: "{{ home_dir }}/dotfiles/dunst/dunstrc", dest: "{{ home_dir }}/.config/dunst/dunstrc" }
        - { src: "{{ home_dir }}/dotfiles/rofi/dracula.rasi", dest: "{{ home_dir }}/.config/rofi" }
      tags: dotfiles, symlinks
