- hosts: localhost
  become: true
  gather_facts: false
  vars:
    dotfiles: https://github.com/marcobompani/dotfiles
    home_user: marco
    home_dir: "/home/{{ home_user }}"
  vars_prompt:
    - name: password
      prompt: "Enter the password for {{ home_user }}"

  tasks:
    - name: Install basic utils
      pacman:
        name:
          - base-devel
          - tmux
          - git
          - python-pip
          - python-pexpect
          - kitty
          - openssl
          - vim
          - man-db
          - man-pages
          - pyenv
          - python-pipenv
          - cron
          - xorg
          - vlc
          - keepass
          - gimp
          - imagemagick
          - flameshot
          - libreoffice-fresh
          - sudo
          - openssh
          - obsidian
          - nvidia
        state: present
        update_cache: true

    - name: Allow wheel users to have passwordless sudo
      lineinfile:
        path: /etc/sudoers.d/wheel
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"
        mode: 0440
        create: yes
        validate: /usr/bin/visudo -cf %s

    - name: Create user
      user:
        name: {{ home_user }}
        shell: /bin/bash
        groups: wheel
        password: "{{ password | password_hash('sha512') }}"

    - name: Install download utilities
      pacman:
        name:
          - wget
          - curl
        state: present
        update_cache: true

    - name: Install archival utilities
      pacman:
        name:
          - unzip
          - zip
          - bzip2
          - gzip
          - tar
        state: present
        update_cache: true

    - name: Install Sway
      pacman:
        name:
          - sway
        state: present
        update_cache: true

    - name: Enable SDDM
      ansible.builtin.systemd_service:
        name: sddm.service
        enabled: true
        masked: false

    - name: Clone yay
      git:
        repo: https://aur.archlinux.org/yay.git
        dest: /opt/yay

    - name: Prep yay
      file:
        path: /opt/yay
        owner: "{{ home_user }}"
        group: "{{ home_user }}"
        recurse: true

    # https://aur.archlinux.org/packages/yay
    - name: Fix connection refused on proxy.golang.org
      file:
        src: /run/systemd/resolve/stub-resolv.conf
        dest: /etc/resolv.conf
        state: link

    - name: Install yay
      command: makepkg --noconfirm -si
      become_user: "{{ home_user }}"
      args:
        chdir: /opt/yay

    - name: Run yay
      expect:
        command: yay
        timeout: 300
        responses:
          Y/n: Y
      become: true

    - name: Install AUR packages
      command: yay --noconfirm --needed -S {{ item }}
      with_items:
        - google-chrome
      become_user: "{{ home_user }}"

    - name: Clone dotfiles
      git:
        repo: "{{ dotfiles }}"
        dest: "{{ home_dir }}/dotfiles"
      become_user: "{{ home_user }}"

    - name: Make directories
      file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ home_user }}"
        group: "{{ home_user }}"
        mode: "0755"
      with_items:
        - { path: "{{ home_dir }}/.config" }
        - { path: "{{ home_dir }}/.config/polybar" }
        - { path: "{{ home_dir }}/.config/rofi" }
        - { path: "{{ home_dir }}/.config/dunst" }
        - { path: "{{ home_dir }}/.config/picom" }
        - { path: "{{ home_dir }}/.config/flameshot" }

    - name: Link dotfiles
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ home_user }}"
        group: "{{ home_user }}"
        mode: "0644"
        state: link
      with_items:
        - { src: "{{ home_dir }}/dotfiles/tmux/tmux.conf", dest: "{{ home_dir }}/.tmux.conf" }
        - { src: "{{ home_dir }}/dotfiles/bash/bash_aliases", dest: "{{ home_dir }}/.bash_aliases" }
        - { src: "{{ home_dir }}/dotfiles/bash/bashrc", dest: "{{ home_dir }}/.bashrc" }
        - { src: "{{ home_dir }}/dotfiles/polybar/config", dest: "{{ home_dir }}/.config/polybar/config" }
        - { src: "{{ home_dir }}/dotfiles/dunst/dunstrc", dest: "{{ home_dir }}/.config/dunst/dunstrc" }
        - { src: "{{ home_dir }}/dotfiles/rofi/dracula.rasi", dest: "{{ home_dir }}/.config/rofi/arthur.rasi" }
        - { src: "{{ home_dir }}/dotfiles/flameshot/flameshot.ini", dest: "{{ home_dir }}/.config/flameshot/flameshot.ini" }
        - { src: "{{ home_dir }}/dotfiles/arch.jpg", dest: "{{ home_dir }}/Pictures/arch.jpg" }
