- hosts: localhost
  become: true
  gather_facts: false
  vars:
    dotfiles: https://github.com/marcobompani/dotfiles
    home_dir: /home/marco
    home_user: marco

  tasks:
    - name: Installing core pacman packages
      pacman:
        name:
          - base-devel
          - zsh
          - zsh-syntax-highlighting
          - tmux
          - htop
          - tcpdump
          - git
          - python-pip
          - python-pexpect
        state: present
        update_cache: true
      tags: install, packages, pacman

    - name: Clone yay
      git:
        repo: https://aur.archlinux.org/yay.git
        dest: /opt/yay
      tags: yay, git

    - name: Prep yay
      shell: chown -R {{ home_user }}:{{ home_user }} /opt/yay
      tags: yay

    - name: Install yay
      command: makepkg --noconfirm -si
      become: false
      args:
        chdir: /opt/yay
      tags: yay

    - name: Run yay
      expect:
        command: yay
        timeout: 300
        responses:
          Y/n: Y
      become: true
      tags: yay

    - name: Install AUR packages
      command: yay --noconfirm --needed -S {{ item }}
      with_items: 
        - zoom
        - slack-desktop
        - google-chrome
      become_user: "{{ home_user }}"
      tags: aur, install, packages

    - name: Clone dotfiles
      git:
        repo: "{{ dotfiles }}"
        dest: "{{ home_dir }}/dotfiles"
      tags: git, dotfiles

    - name: Prep dotfiles
      shell: chown -R {{ home_user }}:{{ home_user }} /opt/yay
      tags: dotfiles
