- name: Clone dotfiles
  git:
    repo: "{{ dotfiles }}"
    dest: "{{ home_dir }}/dotfiles"
  become_user: "{{ home_user }}"

- name: Make directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ home_user }}"
    group: "{{ home_user }}"
    mode: "0755"
  with_items:
    - { path: "{{ home_dir }}/.config" }
    - { path: "{{ home_dir }}/.SpaceVim.d" }
    - { path: "{{ home_dir }}/.config/kitty" }
    - { path: "{{ home_dir }}/.config/sway" }
    - { path: "{{ home_dir }}/.config/polybar" }
    - { path: "{{ home_dir }}/.config/rofi" }
    - { path: "{{ home_dir }}/.config/dunst" }
    - { path: "{{ home_dir }}/.config/picom" }
    - { path: "{{ home_dir }}/.config/flameshot" }
    - { path: "{{ home_dir }}/Pictures/" }

- name: Link dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ home_user }}"
    group: "{{ home_user }}"
    mode: "0644"
    force: true
    follow: false
    state: link
  with_items:
    - { src: "{{ home_dir }}/dotfiles/tmux/tmux.conf", dest: "{{ home_dir }}/.tmux.conf" }
    - { src: "{{ home_dir }}/dotfiles/sway/config", dest: "{{ home_dir }}/.config/sway/config" }
    - { src: "{{ home_dir }}/dotfiles/kitty/kitty.conf", dest: "{{ home_dir }}/.config/kitty/kitty.conf" }
    - { src: "{{ home_dir }}/dotfiles/bash/bash_aliases", dest: "{{ home_dir }}/.bash_aliases" }
    - { src: "{{ home_dir }}/dotfiles/bash/bashrc", dest: "{{ home_dir }}/.bashrc" }
    - { src: "{{ home_dir }}/dotfiles/polybar/config", dest: "{{ home_dir }}/.config/polybar/config" }
    - { src: "{{ home_dir }}/dotfiles/dunst/dunstrc", dest: "{{ home_dir }}/.config/dunst/dunstrc" }
    - { src: "{{ home_dir }}/dotfiles/rofi/config.rasi", dest: "{{ home_dir }}/.config/rofi/config.rasi" }
    - { src: "{{ home_dir }}/dotfiles/flameshot/flameshot.ini", dest: "{{ home_dir }}/.config/flameshot/flameshot.ini" }
    - { src: "{{ home_dir }}/dotfiles/spacevim/init.toml", dest: "{{ home_dir }}/.SpaceVim.d/init.toml" }
    - { src: "{{ home_dir }}/dotfiles/arch.jpg", dest: "{{ home_dir }}/Pictures/arch.jpg" }
