- name: Upgrade System
  pacman:
    update_cache: true
    upgrade: true
  tags: pacman, upgrade

- include_tasks: pacman.yml
  tags: pacman, packages
- include_tasks: user.yml
- include_tasks: yay.yml
- include_tasks: spacevim.yml
- include_tasks: dotfiles.yml
